#pragma once

#define DISPLAY_WIDTH 48
#define DISPLAY_HEIGHT 84

#define VD_VREF 3.37
#define VD_MULTIPLIER 11.16

#define CURRENT_MULTIPLIER 0.1
#define OFFSET_VOLTAGE 2.51

#define NOKIA_DC_PIN 8
#define NOKIA_RS_PIN 9
#define NOKIA_CS_PIN 10

#define VOLTAGE_PIN_33 A0
#define CURRENT_PIN_33 A1
#define VOLTAGE_PIN_50 A2
#define CURRENT_PIN_50 A3

#define NUM_SAMPLES 10.0

#define PANEL_H_PADDING 2
#define VOLTAGE_VALUE_33_Y 10
#define CURRENT_VALUE_33_Y (VOLTAGE_VALUE_33_Y + 16)

#define VOLTAGE_VALUE_50_Y ((DISPLAY_HEIGHT/2) + 12)
#define CURRENT_VALUE_50_Y (VOLTAGE_VALUE_50_Y + 16)

